package com.wx.diary.pojo;

import java.io.Serializable;

public class Stu implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu.STU_ID
     *
     * @mbggenerated Sat Mar 20 21:31:57 CST 2021
     */
    private String stuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu.STU_NAME
     *
     * @mbggenerated Sat Mar 20 21:31:57 CST 2021
     */
    private String stuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stu
     *
     * @mbggenerated Sat Mar 20 21:31:57 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu.STU_ID
     *
     * @return the value of stu.STU_ID
     *
     * @mbggenerated Sat Mar 20 21:31:57 CST 2021
     */
    public String getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu.STU_ID
     *
     * @param stuId the value for stu.STU_ID
     *
     * @mbggenerated Sat Mar 20 21:31:57 CST 2021
     */
    public void setStuId(String stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu.STU_NAME
     *
     * @return the value of stu.STU_NAME
     *
     * @mbggenerated Sat Mar 20 21:31:57 CST 2021
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu.STU_NAME
     *
     * @param stuName the value for stu.STU_NAME
     *
     * @mbggenerated Sat Mar 20 21:31:57 CST 2021
     */
    public void setStuName(String stuName) {
        this.stuName = stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu
     *
     * @mbggenerated Sat Mar 20 21:31:57 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", stuId=").append(stuId);
        sb.append(", stuName=").append(stuName);
        sb.append("]");
        return sb.toString();
    }
}