package com.wx.diarywar.dao;

import com.wx.diary.pojo.Stu;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface StuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu
     *
     * @mbggenerated Sat Mar 20 21:31:57 CST 2021
     */
    int deleteByPrimaryKey(String stuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu
     *
     * @mbggenerated Sat Mar 20 21:31:57 CST 2021
     */
    int insert(Stu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu
     *
     * @mbggenerated Sat Mar 20 21:31:57 CST 2021
     */
    Stu selectByPrimaryKey(String stuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu
     *
     * @mbggenerated Sat Mar 20 21:31:57 CST 2021
     */
    List<Stu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu
     *
     * @mbggenerated Sat Mar 20 21:31:57 CST 2021
     */
    int updateByPrimaryKey(Stu record);
}